In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [3]:
names = ['id',	'name',	'host_id',	'host_name',	'neighbourhood_group',	'neighbourhood',	'latitude',	
         'longitude',	'room_type',	'price',	'minimum_nights',	'number_of_reviews',	'last_review',	
         'reviews_per_month',	'calculated_host_listings_count',	'availability_365']
df = pd.read_csv('https://raw.githubusercontent.com/lmxy0212/ML_project/master/new-york-city-airbnb-open-data/AB_NYC_2019.csv',
                names=names,na_values='?',header=None)
df = df.dropna()
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,2,6,7,9,10,11,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


id  ...  availability_365
0    id  ...  availability_365
1  2539  ...               365
2  2595  ...               355
4  3831  ...               194
5  5022  ...                 0

[5 rows x 16 columns]

In [4]:
airbnb_name = np.array(df['name'][1:])
reviews_per_month = np.array(df['reviews_per_month'][1:])
n = np.shape(airbnb_name)[0]
print(n)
print(airbnb_name)
print(np.array(reviews_per_month))
print(np.shape(airbnb_name))
print(np.shape(reviews_per_month))


38821
['Clean & quiet apt home by the park' 'Skylit Midtown Castle'
 'Cozy Entire Floor of Brownstone' ... 'Seas The Moment'
 '1B-1B apartment near by Metro' 'Cozy Private Room in Bushwick, Brooklyn']
['0.21' '0.38' '4.64' ... 1.0 2.0 1.0]
(38821,)
(38821,)


In [5]:
vectorizer = CountVectorizer()
bow = vectorizer.fit(airbnb_name)
bow = vectorizer.transform(airbnb_name)
bow

<38821x6961 sparse matrix of type '<class 'numpy.int64'>'
	with 222889 stored elements in Compressed Sparse Row format>

In [27]:
print(bow)
# (seq_num, feature_num)  count
print(vectorizer.vocabulary_.get("great")) #feature number of "great"

  (0, 1180)	1
  (0, 1795)	1
  (0, 2033)	1
  (0, 3397)	1
  (0, 4721)	1
  (0, 5069)	1
  (0, 6033)	1
  (1, 1874)	1
  (1, 4236)	1
  (1, 5566)	1
  (2, 1723)	1
  (2, 2254)	1
  (2, 2713)	1
  (2, 2947)	1
  (2, 4599)	1
  (3, 1180)	1
  (3, 1795)	1
  (3, 1911)	1
  (3, 2713)	1
  (3, 3934)	1
  (3, 4721)	1
  (3, 5664)	1
  (3, 5818)	1
  (4, 1152)	1
  (4, 1655)	1
  :	:
  (38815, 5664)	1
  (38816, 1453)	1
  (38816, 3967)	1
  (38816, 4980)	2
  (38816, 5210)	1
  (38816, 6597)	1
  (38817, 1439)	1
  (38817, 4510)	1
  (38817, 5057)	1
  (38817, 5551)	1
  (38817, 6597)	1
  (38818, 4323)	1
  (38818, 5395)	1
  (38818, 6033)	1
  (38819, 232)	2
  (38819, 1152)	1
  (38819, 1795)	1
  (38819, 4212)	1
  (38819, 4436)	1
  (38820, 1707)	1
  (38820, 1778)	1
  (38820, 2254)	1
  (38820, 3515)	1
  (38820, 4963)	1
  (38820, 5277)	1
3188


In [6]:
X = bow.toarray()
print(X)
print(np.shape(X))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(38821, 6961)


In [12]:
Xtr, Xts, ytr, yts = train_test_split(X, reviews_per_month, test_size = 1/3)
print("Xtr:\n", Xtr, "\nXts:\n",Xts,"\nytr:\n", ytr, "\nyts:\n", yts)
print("\nXtr.shape:", Xtr.shape, "Xts.shape", Xts.shape)
print("\nytr.shape:", ytr.shape, "yts.shape:", yts.shape)
ytr = ytr.astype(np.float)
yts = yts.astype(np.float)

Xtr:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 
Xts:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 
ytr:
 ['0.46' '0.87' 0.41 ... 0.65 '0.22' '0.53'] 
yts:
 [6.18 0.23 '0.19' ... '0.04' '0.02' 3.11]

Xtr.shape: (25880, 6961) Xts.shape (12941, 6961)

ytr.shape: (25880,) yts.shape: (12941,)


In [0]:
def plot_y_and_ypred(t,y,y_pred, y1, y2):
  """
    plot y and ypred again t
    y1, y2 are strings
  """
  plt.plot(t, y,'.')
  plt.plot(t, y_pred)
  plt.legend([y1,y2])
  plt.grid()
  plt.xlabel(y1, fontsize=16)
  plt.ylabel(y2, fontsize=16)

In [8]:
regr = linear_model.LinearRegression()
regr.fit(Xtr,ytr)
y_pred = regr.predict(Xtr)
lossm = np.linalg.norm(y_pred - ytr)**2
print(regr.intercept_)
print(regr.coef_)


TypeError: ignored

In [14]:
print(regr.intercept_)
print(regr.coef_)
lossm = (1/n) * np.linalg.norm(y_pred - ytr)**2
print(lossm)

0.692773606369079
[ 1.18191105e-01 -5.42355370e-01 -4.88447552e-01 ...  0.00000000e+00
  1.65455120e+11  1.08883181e+12]
2.394655315129359
